"""
Integration tests for multi-stem and instrument-specific separation models.

Tests a matrix of models × clips, verifying each output stem correlates
with the committed reference stem generated by the best available model
for that instrument type.

Usage:
    # Run all multi-stem tests (requires model downloads):
    pytest tests/integration/test_multi_stem_verification.py -v -s

    # Run a specific test group:
    pytest tests/integration/test_multi_stem_verification.py -v -s -k "vocal_instrumental"
    pytest tests/integration/test_multi_stem_verification.py -v -s -k "drumsep"
    pytest tests/integration/test_multi_stem_verification.py -v -s -k "karaoke"
    pytest tests/integration/test_multi_stem_verification.py -v -s -k "wind"
    pytest tests/integration/test_multi_stem_verification.py -v -s -k "dereverb"

Reference stems were generated using these best-in-class models:
    - Vocal/Instrumental: bs_roformer_vocals_resurrection_unwa.ckpt
    - 4-stem (drums/bass/other/vocals): htdemucs_ft.yaml
    - DrumSep (kick/snare/toms/hh/ride/crash): MDX23C-DrumSep-aufr33-jarredou.ckpt
      (pipeline: mix → htdemucs_ft drums stem → drumsep)
    - Karaoke: mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt
    - Woodwind: 17_HP-Wind_Inst-UVR.pth
    - De-reverb: dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt
      (pipeline: mix → resurrection vocals → dereverb)
"""

import os
import sys
import re
import tempfile
import shutil
import logging
import pytest
import numpy as np
import librosa

REFERENCE_DIR = "tests/inputs/reference"

# Correlation threshold: how closely must the output match the reference stem?
# Lower than spectrogram SSIM because we're comparing against a different model's
# output, not the same model re-run.
DEFAULT_CORRELATION_THRESHOLD = 0.70


def correlate(file_a, file_b, sr=44100):
    """Compute Pearson correlation between two audio files (mono-mixed)."""
    a, _ = librosa.load(file_a, sr=sr, mono=True)
    b, _ = librosa.load(file_b, sr=sr, mono=True)
    min_len = min(len(a), len(b))
    a, b = a[:min_len], b[:min_len]
    if len(a) < min_len:
        a = np.pad(a, (0, min_len - len(a)))
    return float(np.corrcoef(a, b)[0, 1])


def run_separation(model, input_file, output_dir):
    """Run a single model separation, return list of output paths."""
    from audio_separator.separator import Separator
    sep = Separator(output_dir=output_dir, output_format="FLAC", log_level=logging.WARNING)
    sep.load_model(model)
    return sep.separate(input_file)


def find_stem(output_files, stem_name, output_dir):
    """Find the output file matching a stem name (case-insensitive)."""
    for f in output_files:
        full = f if os.path.isabs(f) else os.path.join(output_dir, f)
        if not os.path.exists(full):
            full = os.path.join(output_dir, os.path.basename(f))
        match = re.search(r'_\(([^)]+)\)', os.path.basename(f))
        if match and match.group(1).lower() == stem_name.lower():
            return full
    return None


# ─── Vocal / Instrumental separation ─────────────────────────────────

VOCAL_INSTRUMENTAL_PARAMS = [
    ("tests/inputs/levee_drums.flac", "ref_levee_drums"),
    ("tests/inputs/clocks_piano.flac", "ref_clocks_piano"),
    ("tests/inputs/sing_sing_sing_brass.flac", "ref_sing_sing_sing_brass"),
    ("tests/inputs/only_time_reverb.flac", "ref_only_time_reverb"),
]


@pytest.mark.parametrize("input_file,ref_prefix", VOCAL_INSTRUMENTAL_PARAMS)
def test_vocal_instrumental_separation(input_file, ref_prefix, tmp_path):
    """Test that vocal/instrumental separation produces stems matching references."""
    model = "bs_roformer_vocals_resurrection_unwa.ckpt"
    output_dir = str(tmp_path)

    output_files = run_separation(model, input_file, output_dir)
    clip = os.path.basename(input_file)
    print(f"\n  {clip} → {model}")

    # Find vocal and instrumental stems (this model labels them "vocals" and "other")
    vocals_file = find_stem(output_files, "vocals", output_dir)
    inst_file = find_stem(output_files, "other", output_dir)

    assert vocals_file, f"No vocals stem found in {output_files}"
    assert inst_file, f"No instrumental stem found in {output_files}"

    ref_vocals = os.path.join(REFERENCE_DIR, f"{ref_prefix}_vocals.flac")
    ref_inst = os.path.join(REFERENCE_DIR, f"{ref_prefix}_instrumental.flac")

    corr_v = correlate(vocals_file, ref_vocals)
    corr_i = correlate(inst_file, ref_inst)
    print(f"    Vocals corr:       {corr_v:.3f}")
    print(f"    Instrumental corr: {corr_i:.3f}")

    assert corr_v > DEFAULT_CORRELATION_THRESHOLD, f"Vocals correlation {corr_v:.3f} below threshold"
    assert corr_i > DEFAULT_CORRELATION_THRESHOLD, f"Instrumental correlation {corr_i:.3f} below threshold"


# ─── 4-stem separation (htdemucs_ft) ─────────────────────────────────

FOUR_STEM_PARAMS = [
    ("tests/inputs/levee_drums.flac", "ref_levee_drums"),
    ("tests/inputs/clocks_piano.flac", "ref_clocks_piano"),
]


@pytest.mark.parametrize("input_file,ref_prefix", FOUR_STEM_PARAMS)
def test_four_stem_separation(input_file, ref_prefix, tmp_path):
    """Test htdemucs_ft 4-stem separation matches references."""
    model = "htdemucs_ft.yaml"
    output_dir = str(tmp_path)

    output_files = run_separation(model, input_file, output_dir)
    clip = os.path.basename(input_file)
    print(f"\n  {clip} → {model}")

    for stem in ["Vocals", "Drums", "Bass", "Other"]:
        stem_file = find_stem(output_files, stem, output_dir)
        assert stem_file, f"No {stem} stem found"

        ref_path = os.path.join(REFERENCE_DIR, f"{ref_prefix}_{stem.lower()}_htdemucs_ft.flac")
        corr = correlate(stem_file, ref_path)
        print(f"    {stem:<8} corr: {corr:.3f}")

        assert corr > DEFAULT_CORRELATION_THRESHOLD, f"{stem} correlation {corr:.3f} below threshold"


# ─── DrumSep pipeline ────────────────────────────────────────────────

def test_drumsep_pipeline(tmp_path):
    """Test drumsep pipeline: mix → htdemucs_ft drums → drumsep kit parts."""
    input_file = "tests/inputs/levee_drums.flac"
    output_dir = str(tmp_path)

    print(f"\n  Step 1: Extract drums from mix using htdemucs_ft")
    step1_files = run_separation("htdemucs_ft.yaml", input_file, output_dir)
    drums_file = find_stem(step1_files, "Drums", output_dir)
    assert drums_file, "No drums stem from htdemucs_ft"

    print(f"  Step 2: Split drums into kit parts using DrumSep")
    step2_files = run_separation("MDX23C-DrumSep-aufr33-jarredou.ckpt", drums_file, output_dir)

    for stem in ["kick", "snare", "toms", "hh", "ride", "crash"]:
        stem_file = find_stem(step2_files, stem, output_dir)
        assert stem_file, f"No {stem} stem from DrumSep"

        ref_path = os.path.join(REFERENCE_DIR, f"ref_levee_drums_{stem}_drumsep.flac")
        corr = correlate(stem_file, ref_path)
        print(f"    {stem:<8} corr: {corr:.3f}")

        assert corr > DEFAULT_CORRELATION_THRESHOLD, f"{stem} correlation {corr:.3f} below threshold"


# ─── Karaoke ─────────────────────────────────────────────────────────
#
# Karaoke models remove lead vocals while preserving backing vocals in
# the instrumental. The test verifies:
# 1. Karaoke output matches its own reference (regression check)
# 2. Karaoke vocal output differs from standard vocal output (confirms
#    the model extracts less — just lead vocals, not all vocals)

KARAOKE_PARAMS = [
    ("tests/inputs/levee_drums.flac", "ref_levee_drums"),
    ("tests/inputs/clocks_piano.flac", "ref_clocks_piano"),
]


@pytest.mark.parametrize("input_file,ref_prefix", KARAOKE_PARAMS)
def test_karaoke_separation(input_file, ref_prefix, tmp_path):
    """Test karaoke model produces output matching references and differs from standard split."""
    karaoke_model = "mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt"
    output_dir = str(tmp_path)

    # Step 1: Run karaoke model
    output_files = run_separation(karaoke_model, input_file, output_dir)
    clip = os.path.basename(input_file)
    print(f"\n  {clip} → karaoke")

    # Step 2: Verify stems match karaoke references
    for stem, ref_suffix in [("Vocals", "vocals_karaoke"), ("Instrumental", "instrumental_karaoke")]:
        stem_file = find_stem(output_files, stem, output_dir)
        assert stem_file, f"No {stem} stem found"

        ref_path = os.path.join(REFERENCE_DIR, f"{ref_prefix}_{ref_suffix}.flac")
        corr = correlate(stem_file, ref_path)
        print(f"    {stem:<15} corr with karaoke ref: {corr:.3f}")
        assert corr > DEFAULT_CORRELATION_THRESHOLD, f"{stem} correlation {corr:.3f} below threshold"

    # Step 3: Verify karaoke vocals differ from standard vocals
    # (karaoke extracts only lead vocals; standard extracts all vocals)
    karaoke_vocals = find_stem(output_files, "Vocals", output_dir)
    standard_vocals_ref = os.path.join(REFERENCE_DIR, f"{ref_prefix}_vocals.flac")
    if os.path.exists(standard_vocals_ref):
        corr_vs_standard = correlate(karaoke_vocals, standard_vocals_ref)
        print(f"    Karaoke vs standard vocals corr: {corr_vs_standard:.3f} (should be < 0.95)")
        # Karaoke vocals should differ from standard vocals
        # (not a hard failure — depends on whether there are backing vocals)
        if corr_vs_standard > 0.95:
            print(f"    NOTE: Karaoke and standard vocals are very similar — clip may lack backing vocals")


# ─── Wind / Brass extraction ─────────────────────────────────────────

def test_wind_instrument_extraction(tmp_path):
    """Test wind instrument extraction on brass-heavy clip."""
    model = "17_HP-Wind_Inst-UVR.pth"
    input_file = "tests/inputs/sing_sing_sing_brass.flac"
    output_dir = str(tmp_path)

    output_files = run_separation(model, input_file, output_dir)
    print(f"\n  sing_sing_sing_brass → wind extraction")

    for stem, ref_name in [("Woodwinds", "ref_sing_sing_sing_brass_woodwinds.flac"),
                           ("No Woodwinds", "ref_sing_sing_sing_brass_no_woodwinds.flac")]:
        stem_file = find_stem(output_files, stem, output_dir)
        assert stem_file, f"No '{stem}' stem found"

        ref_path = os.path.join(REFERENCE_DIR, ref_name)
        corr = correlate(stem_file, ref_path)
        print(f"    {stem:<15} corr: {corr:.3f}")

        assert corr > DEFAULT_CORRELATION_THRESHOLD, f"{stem} correlation {corr:.3f} below threshold"


# ─── De-reverb pipeline ──────────────────────────────────────────────

def test_dereverb_pipeline(tmp_path):
    """Test dereverb pipeline: mix → resurrection vocals → dereverb."""
    input_file = "tests/inputs/only_time_reverb.flac"
    output_dir = str(tmp_path)

    print(f"\n  Step 1: Extract vocals from mix")
    step1_files = run_separation("bs_roformer_vocals_resurrection_unwa.ckpt", input_file, output_dir)
    vocals_file = find_stem(step1_files, "vocals", output_dir)
    assert vocals_file, "No vocals stem from resurrection"

    print(f"  Step 2: De-reverb the vocal stem")
    step2_files = run_separation("dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt", vocals_file, output_dir)

    for stem, ref_name in [("noreverb", "ref_only_time_reverb_vocals_noreverb.flac"),
                           ("reverb", "ref_only_time_reverb_vocals_reverb.flac")]:
        stem_file = find_stem(step2_files, stem, output_dir)
        assert stem_file, f"No '{stem}' stem from dereverb"

        ref_path = os.path.join(REFERENCE_DIR, ref_name)
        corr = correlate(stem_file, ref_path)
        print(f"    {stem:<15} corr: {corr:.3f}")

        assert corr > DEFAULT_CORRELATION_THRESHOLD, f"{stem} correlation {corr:.3f} below threshold"
